[package]
name = "frontend-piston"
version = "0.1.0"
authors = ["Kevin Darlington <kevin@outroot.com>"]

[dependencies]
clap = "2.10"
piston_window = "0.51"
gameboy = { path = "../" }
simplelog = "0.2"
log = "0.3"
time = "0.1"
